In [73]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [74]:
df = pd.read_csv("archive/Metro_Interstate_Traffic_Volume.csv")
df.head()

,holiday,temp,rain_1h,snow_1h,clouds_all,weather_main,weather_description,date_time,traffic_volume
0,NaN,288.28,0.0,0.0,40,Clouds,scattered clouds,2012-10-02 09:00:00,5545
1,NaN,289.36,0.0,0.0,75,Clouds,broken clouds,2012-10-02 10:00:00,4516
2,NaN,289.58,0.0,0.0,90,Clouds,overcast clouds,2012-10-02 11:00:00,4767
3,NaN,290.13,0.0,0.0,90,Clouds,overcast clouds,2012-10-02 12:00:00,5026
4,NaN,291.14,0.0,0.0,75,Clouds,broken clouds,2012-10-02 13:00:00,4918

In [75]:
df["holiday"].value_counts()

holiday
Labor Day                    7
Thanksgiving Day             6
Christmas Day                6
New Years Day                6
Martin Luther King Jr Day    6
Columbus Day                 5
Veterans Day                 5
Washingtons Birthday         5
Memorial Day                 5
Independence Day             5
State Fair                   5
Name: count, dtype: int64

In [76]:
df["holiday"].isna().sum()

48143

In [77]:
len(df)

48204

In [78]:
df.columns

Index(['holiday', 'temp', 'rain_1h', 'snow_1h', 'clouds_all', 'weather_main',
       'weather_description', 'date_time', 'traffic_volume'],
      dtype='object')

In [79]:
df.isna().sum()

holiday                48143
temp                       0
rain_1h                    0
snow_1h                    0
clouds_all                 0
weather_main               0
weather_description        0
date_time                  0
traffic_volume             0
dtype: int64

In [80]:
df["is_holiday"] = df["holiday"].apply(lambda x:0 if x == "None" else 1)

In [81]:
df.head()

,holiday,temp,rain_1h,snow_1h,clouds_all,weather_main,weather_description,date_time,traffic_volume,is_holiday
0,NaN,288.28,0.0,0.0,40,Clouds,scattered clouds,2012-10-02 09:00:00,5545,1
1,NaN,289.36,0.0,0.0,75,Clouds,broken clouds,2012-10-02 10:00:00,4516,1
2,NaN,289.58,0.0,0.0,90,Clouds,overcast clouds,2012-10-02 11:00:00,4767,1
3,NaN,290.13,0.0,0.0,90,Clouds,overcast clouds,2012-10-02 12:00:00,5026,1
4,NaN,291.14,0.0,0.0,75,Clouds,broken clouds,2012-10-02 13:00:00,4918,1

In [82]:
df.drop(columns ="holiday",axis =1)

,temp,rain_1h,snow_1h,clouds_all,weather_main,weather_description,date_time,traffic_volume,is_holiday
0,288.28,0.0,0.0,40,Clouds,scattered clouds,2012-10-02 09:00:00,5545,1
1,289.36,0.0,0.0,75,Clouds,broken clouds,2012-10-02 10:00:00,4516,1
2,289.58,0.0,0.0,90,Clouds,overcast clouds,2012-10-02 11:00:00,4767,1
3,290.13,0.0,0.0,90,Clouds,overcast clouds,2012-10-02 12:00:00,5026,1
4,291.14,0.0,0.0,75,Clouds,broken clouds,2012-10-02 13:00:00,4918,1
...,...,...,...,...,...,...,...,...,...
48199,283.45,0.0,0.0,75,Clouds,broken clouds,2018-09-30 19:00:00,3543,1
48200,282.76,0.0,0.0,90,Clouds,overcast clouds,2018-09-30 20:00:00,2781,1
48201,282.73,0.0,0.0,90,Thunderstorm,proximity thunderstorm,2018-09-30 21:00:00,2159,1
48202,282.09,0.0,0.0,90,Clouds,overcast clouds,2018-09-30 22:00:00,1450,1
48203,282.12,0.0,0.0,90,Clouds,overcast clouds,2018-09-30 23:00:00,954,1

In [83]:
df = df.drop(columns ="holiday",axis = 1)

In [84]:
df["date_time"] = pd.to_datetime(df["date_time"])

In [85]:
df["date_time"]

0       2012-10-02 09:00:00
1       2012-10-02 10:00:00
2       2012-10-02 11:00:00
3       2012-10-02 12:00:00
4       2012-10-02 13:00:00
                ...
48199   2018-09-30 19:00:00
48200   2018-09-30 20:00:00
48201   2018-09-30 21:00:00
48202   2018-09-30 22:00:00
48203   2018-09-30 23:00:00
Name: date_time, Length: 48204, dtype: datetime64[ns]

In [86]:
df["hour"] = df["date_time"].dt.hour
df["month"] = df["date_time"].dt.month
df["weekend"] = df["date_time"].dt.weekday

In [87]:
df["weekend"].value_counts()

weekend
0    7072
2    6930
6    6872
1    6846
4    6836
5    6831
3    6817
Name: count, dtype: int64

In [88]:
df["is_weekend"] = df["weekend"].apply(lambda x:0 if x<5 else 1)

In [89]:
df["is_weekend"].value_counts()

is_weekend
0    34501
1    13703
Name: count, dtype: int64

In [90]:
df["traffic_status"] = df["traffic_volume"].apply(lambda x:0 if x<4000 else 1)
df["traffic_status"].value_counts()

traffic_status
0    27265
1    20939
Name: count, dtype: int64

In [91]:
df.columns

Index(['temp', 'rain_1h', 'snow_1h', 'clouds_all', 'weather_main',
       'weather_description', 'date_time', 'traffic_volume', 'is_holiday',
       'hour', 'month', 'weekend', 'is_weekend', 'traffic_status'],
      dtype='object')

In [92]:

df["snow_1hr"] = df["snow_1h"].apply(lambda x:0 if x<1 else 1)
df["snow_1hr"].value_counts()
df["snow_1h"].value_counts()

snow_1h
0.00    48141
0.05       14
0.06       12
0.51        6
0.25        6
0.13        6
0.10        6
0.32        5
0.17        3
0.44        2
0.08        2
0.21        1
Name: count, dtype: int64

In [93]:
df["rain_1hr"] = df["rain_1h"].apply(lambda x:0 if x<1 else 1)

In [94]:
features = [
    'temp',
    'clouds_all',
    'rain_1hr',
    'snow_1hr',
    'weather_main',
    'hour',
    'month',
    'is_weekend'
]

X = df[features]
y = df['traffic_status']

In [95]:
df = df.sort_values("date_time")

split_index = int(len(df) * 0.8)

train = df.iloc[:split_index]
test = df.iloc[split_index:]

X_train = train[features]
y_train = train['traffic_status']

X_test = test[features]
y_test = test['traffic_status']

In [96]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

categorical_features = ['weather_main']

preprocessor = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_features)
    ],
    remainder='passthrough'
)

In [97]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators = 100,random_state = 42)

In [98]:
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier

pipeline = Pipeline(steps=[
    ('preprocessing', preprocessor),
    ('model', RandomForestClassifier(
        n_estimators=200,
        random_state=42
    ))
])

In [99]:
from sklearn.pipeline import Pipeline
pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['weather_main'])])),
                ('model',
                 RandomForestClassifier(n_estimators=200, random_state=42))])

In [100]:
from sklearn.metrics import accuracy_score, classification_report

y_pred = pipeline.predict(X_test)

print("Test Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Test Accuracy: 0.9306088580022819
              precision    recall  f1-score   support

           0       0.95      0.92      0.94      5482
           1       0.90      0.94      0.92      4159

    accuracy                           0.93      9641
   macro avg       0.93      0.93      0.93      9641
weighted avg       0.93      0.93      0.93      9641

In [101]:
train_pred = pipeline.predict(X_train)

print("Train Accuracy:", accuracy_score(y_train, train_pred))
print("Test Accuracy:", accuracy_score(y_test, y_pred))

Train Accuracy: 0.9995332313357363
Test Accuracy: 0.9306088580022819

In [102]:
model = pipeline.named_steps['model']

importances = model.feature_importances_

feature_names = pipeline.named_steps['preprocessing'].get_feature_names_out()

importance_df = pd.DataFrame({
    'feature': feature_names,
    'importance': importances
}).sort_values(by='importance', ascending=False)

importance_df.head(10)

                     feature  importance
15           remainder__hour    0.735714
11           remainder__temp    0.125034
17     remainder__is_weekend    0.075103
16          remainder__month    0.027043
12     remainder__clouds_all    0.023031
1   cat__weather_main_Clouds    0.003327
0    cat__weather_main_Clear    0.001697
5     cat__weather_main_Mist    0.001635
13       remainder__rain_1hr    0.001461
6     cat__weather_main_Rain    0.001446

In [103]:
import joblib
joblib.dump(pipeline, "traffic_analysis.pkl")

['traffic_analysis.pkl']

In [104]:
df["traffic_status"].value_counts()

traffic_status
0    27265
1    20939
Name: count, dtype: int64

In [105]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))

[[5055  427]
 [ 242 3917]]

In [106]:
df["traffic_volume"].describe

<bound method NDFrame.describe of 0        5545
1        4516
2        4767
3        5026
4        4918
         ...
48199    3543
48200    2781
48201    2159
48202    1450
48203     954
Name: traffic_volume, Length: 48204, dtype: int64>